# Generated by Django 4.2.2 on 2023-12-21 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_alter_to_do_item_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='to_do_item',
            new_name='ToDoItem',
        ),
    ]
