# Generated by Django 4.2.2 on 2023-12-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_rename_to_do_item_todoitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='deadline',
            field=models.DateTimeField(blank=True),
        ),
    ]
