# Generated by Django 4.2.2 on 2023-12-21 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0006_alter_todoitem_deadline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='deadline',
            new_name='deadlines',
        ),
    ]
