# Generated by Django 4.2.2 on 2023-12-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0007_rename_deadline_todoitem_deadlines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='deadlines',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
