# Generated by Django 4.2.2 on 2023-12-21 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0008_alter_todoitem_deadlines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='deadlines',
        ),
    ]
