# Generated by Django 4.2.2 on 2023-12-21 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0009_remove_todoitem_deadlines'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ToDoItem',
            new_name='ToDoItems',
        ),
    ]
