# Generated by Django 4.2.2 on 2023-12-21 10:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0013_todo_task_delete_itemcreate_delete_todoitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo_task',
            name='deadline',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
