# Generated by Django 4.2.2 on 2023-12-21 10:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0015_alter_todo_task_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo_task',
            name='deadline',
            field=models.DateTimeField(default=datetime.timezone),
        ),
    ]
